Importaciones necesarias

# Creación de la base de datos

In [3]:
import warnings
warnings.filterwarnings('ignore')
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

load_dotenv()

DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = "postgres"  # Base existente para crear otras bases

DATABASE_URL = URL.create(
    drivername="postgresql+psycopg2",
    username=DB_USER,
    password=DB_PASSWORD,
    host=DB_HOST,
    port=int(DB_PORT),
    database=DB_NAME
)

engine = create_engine(
    DATABASE_URL,
    isolation_level="AUTOCOMMIT"
)

try:
    with engine.connect() as connection:
        connection.execute(text("CREATE DATABASE clip_pay"))
        print("Base de datos creada exitosamente.")
except Exception as e:
    print(f"No se pudo crear la base de datos: {e}")
finally:
    engine.dispose()

No se pudo crear la base de datos: (psycopg2.errors.DuplicateDatabase) la base de datos «clip_pay» ya existe

[SQL: CREATE DATABASE clip_pay]
(Background on this error at: https://sqlalche.me/e/20/f405)

Creación de tablas

In [ ]:
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base

load_dotenv()

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/clip_pay"
)


# Conexión a PostgreSQL
engine = create_engine(
    'DATABASE_URL'
)

# Crear sesión
Session = sessionmaker(bind=engine)
session = Session()

# Clase base para modelos ORM
Base = declarative_base()

In [ ]:
from sqlalchemy import (
    create_engine,
    Column,
    Integer,
    String,
    Float,
    DateTime,
    ForeignKey,
    CheckConstraint
)

from sqlalchemy.orm import declarative_base


Base = declarative_base()

load_dotenv()

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/clip_pay"
)

engine = create_engine(
    "DATABASE_URL"
)

class Customer(Base):
    __tablename__ = 'customers'

    customer_id = Column(Integer, primary_key=True)

    age = Column(Integer, nullable=False)

    city = Column(String(100), nullable=False)

    # Restricciones para validar datos
    __table_args__ = (
        CheckConstraint(
            "age >= 18",
            name="ck_customer_age"
        ),
    )


class Merchant(Base):
    __tablename__ = 'merchants'

    merchant_id = Column(Integer, primary_key=True)

    merchant_name = Column(String(100), nullable=False)

    category = Column(String(100), nullable=False)

    # Restricciones para validar datos
    __table_args__ = (
        CheckConstraint(
            "length(merchant_name) > 0",
            name="ck_merchant_name_no_vacio"
        ),
    )


class PaymentMethod(Base):
    __tablename__ = 'payment_methods'

    payment_method_id = Column(Integer, primary_key=True)

    customer_id = Column(
        Integer,
        ForeignKey('customers.customer_id'),
        nullable=False
    )

    method_type = Column(String(50), nullable=False)

    # Restricciones para validar datos
    __table_args__ = (
        CheckConstraint(
            "length(method_type) > 0",
            name="ck_payment_method_type_no_vacio"
        ),
    )


class Transaction(Base):
    __tablename__ = 'transactions'

    transaction_id = Column(Integer, primary_key=True)

    customer_id = Column(
        Integer,
        ForeignKey('customers.customer_id'),
        nullable=False
    )

    merchant_id = Column(
        Integer,
        ForeignKey('merchants.merchant_id'),
        nullable=False
    )

    payment_method_id = Column(
        Integer,
        ForeignKey('payment_methods.payment_method_id'),
        nullable=False
    )

    amount = Column(Float, nullable=False)

    transaction_date = Column(DateTime, nullable=False)

    # Restricciones para validar datos
    __table_args__ = (
        CheckConstraint(
            "amount > 0",
            name="ck_transaction_amount_positive"
        ),
    )


Base.metadata.create_all(engine)
print("Tablas creadas correctamente.")

Tablas creadas correctamente.

Llenado de base de datos

In [83]:
# Conexión a PostgreSQL
engine     = create_engine('postgresql+psycopg2://postgres:Manriz01@localhost:5432/clip_pay')
connection = engine.raw_connection()


# Leer los archivos CSV
customers = pd.read_csv("customers.csv")
merchants = pd.read_csv("merchants.csv")
payment_methods = pd.read_csv("payment_methods.csv")
transactions = pd.read_csv("transactions.csv")


# Mostrar los datos antes de insertarlos
print("Customers:")
print(customers.head())

print("\nMerchants:")
print(merchants.head())

print("\nPayment Methods:")
print(payment_methods.head())

print("\nTransactions:")
print(transactions.head())


# Insertar los datos en PostgreSQL
customers.to_sql(
    "customers",
    engine,
    if_exists="append",
    index=False
)

merchants.to_sql(
    "merchants",
    engine,
    if_exists="append",
    index=False
)

payment_methods.to_sql(
    "payment_methods",
    engine,
    if_exists="append",
    index=False
)

transactions.to_sql(
    "transactions",
    engine,
    if_exists="append",
    index=False
)


print("\nDatos cargados correctamente.")

Customers:
   customer_id  age              city
0            1   58            Mérida
1            2   25         Monterrey
2            3   19           Tijuana
3            4   65   San Luis Potosí
4            5   35  Ciudad de México

Merchants:
   merchant_id merchant_name                category
0            1       Walmart            Supermercado
1            2       Soriana            Supermercado
2            3      Chedraui            Supermercado
3            4          OXXO  Tienda de conveniencia
4            5      7-Eleven  Tienda de conveniencia

Payment Methods:
   payment_method_id  customer_id         method_type
0                  1            1  Tarjeta de crédito
1                  2            2  Tarjeta de crédito
2                  3            2  Transferencia SPEI
3                  4            3   Billetera digital
4                  5            3  Transferencia SPEI

Transactions:
   transaction_id  customer_id  merchant_id  payment_method_id  amount  \
0               1           49            7                 95  386.68
1               2           34           15                 65  154.15
2               3            2           19                  2  285.09
3               4           46            2                 87  134.46
4               5           18           16                 34  312.09

      transaction_date
0  2026-01-01 02:10:27
1  2026-01-01 17:47:12
2  2026-01-02 14:09:18
3  2026-01-05 16:26:09
4  2026-01-06 12:45:13

Datos cargados correctamente.

# Ejemplos de Consultas

PARA VOLVER A HACER CONSULTAS
Ejecuta:

In [ ]:
load_dotenv()

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/clip_pay"
)

# Conexión a PostgreSQL
engine     = create_engine('DATABASE_URL')
connection = engine.raw_connection()

SELECT

In [85]:
connection.rollback()

print("Todo sobre los tres primeros clientes")
pd.read_sql(
    'SELECT * FROM customers ' \
    'LIMIT 3', 
    connection
    )

Todo sobre los tres primeros clientes

   customer_id  age       city
0            1   58     Mérida
1            2   25  Monterrey
2            3   19    Tijuana

WHERE

In [ ]:
connection.rollback()

print("Clientes mayores de 30 años y que sean de CDMX")
pd.read_sql(
    "SELECT * FROM customers " \
    "WHERE age >= 30 AND city = 'Ciudad de México'",
    connection
    )

Clientes mayores de 30 años y que sean de CDMX

   customer_id  age              city
0            5   35  Ciudad de México
1           11   61  Ciudad de México
2           14   52  Ciudad de México
3           23   50  Ciudad de México
4           30   62  Ciudad de México
5           34   46  Ciudad de México
6           36   35  Ciudad de México

GROUP BY

In [ ]:
connection.rollback()

print("Número de clientes por ciudad")
pd.read_sql(
    "SELECT city, " \
    "COUNT(*) AS total_customers " \
    "FROM customers " \
    "GROUP BY city",
    connection
    )

Número de clientes por ciudad

               city  total_customers
0            Mérida                2
1   San Luis Potosí                4
2            Puebla                4
3       Guadalajara                8
4           Tijuana                6
5            Toluca                7
6  Ciudad de México                7
7         Querétaro                2
8         Monterrey                4
9            Cancún                6

In [ ]:
connection.rollback()

print("Ventas por cliente")
pd.read_sql(
    "SELECT customer_id, " \
    "SUM(amount) AS total_spent " \
    "FROM transactions " \
    "GROUP BY customer_id " \
    "LIMIT 3",
    connection
    )

Ventas por cliente

   customer_id  total_spent
0           42      2021.25
1           29      1388.57
2            4      1905.76

ORDER BY

In [32]:
connection.rollback()

print("Clientes de mayor a menor edad")
pd.read_sql(
    "SELECT * FROM customers " \
    "ORDER BY age DESC;",
    connection
    )

Clientes de mayor a menor edad

    customer_id  age              city
0            13   75            Puebla
1            38   73         Monterrey
2            41   69         Monterrey
3            37   69            Cancún
4            49   66       Guadalajara
5            40   66           Tijuana
6            12   65            Cancún
7             4   65   San Luis Potosí
8             9   65            Mérida
9            28   63   San Luis Potosí
10           30   62  Ciudad de México
11           43   62       Guadalajara
12           11   61  Ciudad de México
13           29   59            Toluca
14            1   58            Mérida
15           24   56            Toluca
16           35   55            Puebla
17           16   55           Tijuana
18           26   53            Puebla
19           31   52            Toluca
20           14   52  Ciudad de México
21           23   50  Ciudad de México
22           34   46  Ciudad de México
23           44   45            Toluca
24           17   45           Tijuana
25           32   44            Toluca
26           50   39            Toluca
27           45   39         Querétaro
28            5   35  Ciudad de México
29           36   35  Ciudad de México
30           46   35            Cancún
31            6   33       Guadalajara
32            7   32            Cancún
33           22   32           Tijuana
34           33   32           Tijuana
35           48   31         Monterrey
36           21   31            Cancún
37           27   30   San Luis Potosí
38           42   28            Cancún
39           47   27   San Luis Potosí
40            8   26       Guadalajara
41            2   25         Monterrey
42           10   24            Toluca
43           20   23       Guadalajara
44           15   23       Guadalajara
45           18   20       Guadalajara
46           19   19            Puebla
47           25   19       Guadalajara
48            3   19           Tijuana
49           39   18         Querétaro

In [35]:
connection.rollback()

print("Suma de gastos por cliente ordenados de mayor a menor")
pd.read_sql(
    "SELECT customer_id, SUM(amount) AS total_spent " \
    "FROM transactions " \
    "GROUP BY customer_id " \
    "ORDER BY total_spent DESC;",
    connection
    )

Suma de gastos por cliente ordenados de mayor a menor

    customer_id  total_spent
0            27      8535.01
1            33      8468.87
2            31      6456.21
3            46      6003.06
4            22      5431.76
5            20      4204.00
6            38      3976.85
7             7      3834.47
8            17      3754.28
9            36      3569.78
10           24      3454.82
11           30      3111.15
12           47      2909.77
13           44      2834.29
14           11      2824.00
15           35      2803.60
16            5      2709.45
17            2      2535.41
18            8      2452.31
19           37      2355.46
20           13      2253.92
21            9      2182.14
22           18      2106.30
23           48      2061.79
24           42      2021.25
25           23      1933.73
26            4      1905.76
27           41      1881.34
28           15      1854.52
29           26      1827.77
30           16      1819.79
31           10      1763.63
32           49      1728.64
33           43      1716.61
34            6      1658.94
35           25      1610.92
36           29      1388.57
37           34      1319.56
38           28      1254.08
39           45      1238.10
40           21       932.09
41           39       874.09
42           19       829.39
43            3       621.99
44           50       615.93
45            1       432.44
46           40       408.29
47           12       235.68
48           14       176.36
49           32       101.88

HAVING

In [36]:
connection.rollback()

print("Clientes que han gastado más de $5,000")
pd.read_sql(
    "SELECT " \
    "customer_id, " \
    "SUM(amount) AS total_spent " \
    "FROM transactions " \
    "GROUP BY customer_id " \
    "HAVING SUM(amount) > 5000;",
    connection
    )

Clientes que han gastado más de $5,000

   customer_id  total_spent
0           46      6003.06
1           31      6456.21
2           22      5431.76
3           33      8468.87
4           27      8535.01

JOIN - combina información de varias tablas.

In [37]:
connection.rollback()

print("Transacciones con el id & ciudad del cliente y el nombre del comercio")
pd.read_sql(
    "SELECT " \
    "t.transaction_id, " \
    "c.customer_id, " \
    "c.city, " \
    "m.merchant_name, " \
    "t.amount " \
    "FROM transactions t " \
    "JOIN customers c " \
    "ON t.customer_id = c.customer_id " \
    "JOIN merchants m " \
    "ON t.merchant_id = m.merchant_id;",
    connection
    )

Transacciones con el id & ciudad del cliente y el nombre del comercio

     transaction_id  customer_id         city  merchant_name  amount
0               255            1       Mérida     Home Depot  114.11
1                48            1       Mérida      Cinépolis   24.03
2               159            1       Mérida  Mercado Libre  193.04
3                55            1       Mérida           OXXO   20.86
4                13            1       Mérida       Chedraui   80.40
..              ...          ...          ...            ...     ...
295             215           49  Guadalajara       Chedraui  212.35
296             124           49  Guadalajara        Soriana  154.49
297              66           50       Toluca         Telcel  313.65
298             199           50       Toluca         Telcel   52.57
299             212           50       Toluca      Liverpool  249.71

[300 rows x 5 columns]

INNER JOIN - devuelve solamente los registros que tienen coincidencia en ambas tablas.

In [46]:
connection.rollback()

print("Transacciones por cliente, solo aparecen clientes con transacciones")
pd.read_sql(
    "SELECT " \
    "c.customer_id, " \
    "c.city, " \
    "t.amount " \
    "FROM customers c " \
    "INNER JOIN transactions t " \
    "ON c.customer_id = t.customer_id;",
    connection
    )

Transacciones por cliente, solo aparecen clientes con transacciones

     customer_id         city  amount
0              1       Mérida  114.11
1              1       Mérida  193.04
2              1       Mérida   20.86
3              1       Mérida   24.03
4              1       Mérida   80.40
..           ...          ...     ...
295           49  Guadalajara  331.89
296           49  Guadalajara  386.68
297           50       Toluca  249.71
298           50       Toluca   52.57
299           50       Toluca  313.65

[300 rows x 3 columns]

LEFT JOIN - devuelve todos los registros de la tabla de la izquierda, aunque no tengan coincidencia.

In [50]:
connection.rollback()

print("Transacciones por cliente, aparecen aunque no tenga transacciones un cliente")
pd.read_sql(
    "SELECT " \
    "c.customer_id, " \
    "c.city, " \
    "t.amount " \
    "FROM customers c " \
    "LEFT JOIN transactions t " \
    "ON c.customer_id = t.customer_id;",
    connection
    )

Transacciones por cliente, aparecen aunque no tenga transacciones un cliente

     customer_id         city  amount
0              1       Mérida  114.11
1              1       Mérida  193.04
2              1       Mérida   20.86
3              1       Mérida   24.03
4              1       Mérida   80.40
..           ...          ...     ...
295           49  Guadalajara  331.89
296           49  Guadalajara  386.68
297           50       Toluca  249.71
298           50       Toluca   52.57
299           50       Toluca  313.65

[300 rows x 3 columns]

AVG

In [58]:
connection.rollback()

print("Promedio gastado por cliente ordenando de manera descendente")
pd.read_sql(
    "SELECT " \
    "customer_id, " \
    "AVG(amount) AS average_transaction " \
    "FROM transactions " \
    "GROUP BY customer_id " \
    "ORDER BY average_transaction DESC;",
    connection
    )

Promedio gastado por cliente ordenando de manera descendente

    customer_id  average_transaction
0            27          1422.501667
1            33           940.985556
2            46           857.580000
3            31           807.026250
4            22           775.965714
5            47           727.442500
6            41           627.113333
7            35           560.720000
8            20           525.500000
9            48           515.447500
10           38           497.106250
11           17           469.285000
12           16           454.947500
13            5           451.575000
14           36           446.222500
15           34           439.853333
16            9           436.428000
17            7           426.052222
18            2           422.568333
19           44           404.898571
20           42           404.250000
21            8           350.330000
22           30           345.683333
23           23           322.288333
24           25           322.184000
25           13           321.988571
26            4           317.626667
27           24           314.074545
28           11           313.777778
29           28           313.520000
30           15           309.086667
31           18           263.287500
32           37           261.717778
33           26           261.110000
34           43           245.230000
35           21           233.022500
36           29           231.428333
37           39           218.522500
38           49           216.080000
39            6           207.367500
40           19           207.347500
41            3           207.330000
42           50           205.310000
43           40           204.145000
44           45           176.871429
45           10           176.363000
46           12           117.840000
47           32           101.880000
48           14            88.180000
49            1            86.488000

MIN / MAX

In [59]:
connection.rollback()

print("Mínimo monto de una transacción y máximo monto de una transacción")
pd.read_sql(
    "SELECT " \
    "MIN(amount) AS smallest_transaction, " \
    "MAX(amount) AS largest_transaction " \
    "FROM transactions;",
    connection
    )

Mínimo monto de una transacción y máximo monto de una transacción

   smallest_transaction  largest_transaction
0                 14.49              6344.64

DISTINCT - obtiene valores únicos.

In [60]:
connection.rollback()

print("Métodos de pago")
pd.read_sql(
    "SELECT DISTINCT method_type " \
    "FROM payment_methods;",
    connection
    )

Métodos de pago

          method_type
0            Efectivo
1   Tarjeta de débito
2  Transferencia SPEI
3   Billetera digital
4  Tarjeta de crédito

CASE WHEN - como un if and else

In [63]:
connection.rollback()

print("Clasificación de nuestros clientes por edad")
pd.read_sql(
    "SELECT " \
    "   customer_id, " \
    "   age, " \
    "   CASE " \
    "       WHEN age < 25 THEN 'Joven' " \
    "       WHEN age BETWEEN 25 AND 40 THEN 'Adulto' " \
    "       ELSE 'Adulto mayor' " \
    "   END AS age_group " \
    "FROM customers " \
    "LIMIT 3;",
    connection
    )

Clasificación de nuestros clientes por edad

   customer_id  age     age_group
0            1   58  Adulto mayor
1            2   25        Adulto
2            3   19         Joven

SUBQUERIES - consulta dentro de otra consulta

In [64]:
connection.rollback()

print("Transacciones superiores al promedio.")
pd.read_sql(
    "SELECT * " \
    "FROM transactions " \
    "WHERE amount > ( " \
    "   SELECT AVG(amount) " \
    "   FROM transactions" \
    ");",
    connection
    )

Transacciones superiores al promedio.

,transaction_id,customer_id,merchant_id,payment_method_id,amount,transaction_date
0,8,28,14,53,514.94,2026-01-09 23:16:03
1,9,4,13,6,436.56,2026-01-10 21:41:07
2,12,36,4,70,431.88,2026-01-11 20:23:32
3,15,30,10,57,855.30,2026-01-16 05:26:17
4,18,38,16,75,1135.09,2026-01-23 21:29:42
...,...,...,...,...,...,...
75,285,23,5,43,414.65,2026-09-22 07:25:10
76,288,36,9,70,426.78,2026-09-25 23:53:45
77,290,47,20,91,940.65,2026-09-26 18:26:11
78,298,4,10,6,716.00,2026-10-04 07:35:42
79,300,33,15,63,892.32,2026-10-06 07:27:18

CTE - crea una variable con un resultado que después se puede utilizar

In [66]:
connection.rollback()

print("Transacciones por cliente mayores a 5000")
pd.read_sql(
    "WITH customer_spending AS (" \
    "   SELECT " \
    "       customer_id, " \
    "       SUM(amount) AS total_spent " \
    "   FROM transactions " \
    "   GROUP BY customer_id" \
    ") " \
    "SELECT * " \
    "FROM customer_spending " \
    "WHERE total_spent > 5000;",
    connection
    )

Transacciones por cliente mayores a 5000

   customer_id  total_spent
0           46      6003.06
1           31      6456.21
2           22      5431.76
3           33      8468.87
4           27      8535.01

FUNCIONES DE FECHA

In [ ]:
connection.rollback()

print("Transacciones por año")
pd.read_sql(
    "SELECT " \
    "   EXTRACT(YEAR FROM transaction_date::date) AS year," \
    "   COUNT(*) AS transactions " \
    "FROM transactions " \
    "GROUP BY EXTRACT(YEAR FROM transaction_date::date) " \
    "ORDER BY EXTRACT(YEAR FROM transaction_date::date);",
    connection
)

Transacciones superiores al promedio.

     year  transactions
0  2026.0           300

In [ ]:
connection.rollback()

print("Transacciones por mes")

pd.read_sql(
    "SELECT " \
    "   EXTRACT(MONTH FROM transaction_date::date) AS month," \
    "   COUNT(*) AS transactions " \
    "FROM transactions " \
    "GROUP BY EXTRACT(MONTH FROM transaction_date::date) " \
    "ORDER BY EXTRACT(MONTH FROM transaction_date::date);",
    connection
)

Transacciones superiores al promedio.

   month  transactions
0    1.0            28
1    2.0            38
2    3.0            36
3    4.0            23
4    5.0            36
5    6.0            32
6    7.0            37
7    8.0            34
8    9.0            32
9   10.0             4

In [76]:
connection.rollback()

print("Ventas por año")

pd.read_sql(
    "SELECT " \
    "   EXTRACT(YEAR FROM transaction_date::date) AS YEAR," \
    "   SUM(amount) AS total_sales " \
    "FROM transactions " \
    "GROUP BY EXTRACT(YEAR FROM transaction_date::date) " \
    "ORDER BY EXTRACT(YEAR FROM transaction_date::date);",
    connection
)

Ventas por año

     year  total_sales
0  2026.0    122980.05

Diferencia entre WHERE y HAVING - WHERE filtra filas antes de agrupar y HAVING filtra grupos después de agrupar

OVER

In [ ]:
connection.rollback()

print("Crea una columna extra con el monto máximo por cliente")

pd.read_sql(
    "SELECT " \
    "   t.transaction_id, " \
    "   c.customer_id, " \
    "   c.city, t.amount, " \
    "   MAX(t.amount) OVER (" \
    "       PARTITION BY t.customer_id" \
    "   ) AS max_amount " \
    "FROM transactions t " \
    "JOIN customers c " \
    "   ON t.customer_id = c.customer_id " \
    "ORDER BY c.customer_id, t.transaction_date;",
    connection
)

Los 10 clientes que más dinero han gastado en transacciones superiores a $100, mostrando su ciudad, cantidad de transacciones y gasto total

     transaction_id  customer_id         city  amount  max_amount
0                13            1       Mérida   80.40      193.04
1                48            1       Mérida   24.03      193.04
2                55            1       Mérida   20.86      193.04
3               159            1       Mérida  193.04      193.04
4               255            1       Mérida  114.11      193.04
..              ...          ...          ...     ...         ...
295             215           49  Guadalajara  212.35      386.68
296             296           49  Guadalajara  285.81      386.68
297              66           50       Toluca  313.65      313.65
298             199           50       Toluca   52.57      313.65
299             212           50       Toluca  249.71      313.65

[300 rows x 5 columns]

CONSULTA INTEGRADORA 1

In [64]:
connection.rollback()

print("Los 10 clientes que más dinero han gastado en transacciones superiores a $100, mostrando su ciudad, cantidad de transacciones y gasto total")

pd.read_sql(
    "SELECT " \
    "   c.customer_id, " \
    "   c.city," \
    "   COUNT(t.transaction_id) AS transaction_count, " \
    "   SUM(t.amount) AS total_spent, " \
    "   AVG(t.amount) AS average_transaction " \
    "FROM customers c " \
    "INNER JOIN transactions t " \
    "   ON c.customer_id = t.customer_id " \
    "WHERE t.amount > 100 " \
    "GROUP BY " \
    "   c.customer_id, " \
    "   c.city " \
    "HAVING SUM(t.amount) > 1000 " \
    "ORDER BY total_spent DESC " \
    "LIMIT 10;",
    connection
)

Los 10 clientes que más dinero han gastado en transacciones superiores a $100, mostrando su ciudad, cantidad de transacciones y gasto total

,customer_id,city,transaction_count,total_spent,average_transaction
0,27,San Luis Potosí,5,8462.43,1692.486000
1,33,Tijuana,8,8400.65,1050.081250
2,31,Toluca,8,6456.21,807.026250
3,46,Cancún,6,5926.48,987.746667
4,22,Tijuana,6,5350.32,891.720000
5,20,Guadalajara,7,4133.39,590.484286
6,38,Monterrey,7,3900.22,557.174286
7,17,Tijuana,6,3601.86,600.310000
8,7,Cancún,5,3562.00,712.400000
9,36,Ciudad de México,7,3498.82,499.831429

CONSULTA INTEGREADORA 2

In [76]:
connection.rollback()

print(
    "Contar las transacciones mayores o iguales a 1000 por ciudad, "
    "calcular su porcentaje respecto al total de transacciones "
    "de cada ciudad y obtener el monto máximo por ciudad."
)

pd.read_sql(
    "SELECT c.city, " \
    "   SUM(" \
    "       CASE " \
    "           WHEN t.amount >= 1000 THEN 1 " \
    "           ELSE 0 " \
    "       END" \
    "   ) AS num_trans_200, " \
    "   ROUND(" \
    "       100.0 * SUM(" \
    "           CASE WHEN t.amount >= 1000 THEN 1 " \
    "           ELSE 0 " \
    "       END" \
    "   ) / COUNT(*)," \
    "   1" \
    "   ) AS num_trans_200_rate, " \
    "   MAX(t.amount) AS max_amount_city " \
    "FROM customers c " \
    "INNER JOIN transactions t " \
    "   ON c.customer_id = t.customer_id " \
    "GROUP BY c.city " \
    "ORDER BY num_trans_200 DESC;",
    connection
)

Contar las transacciones mayores o iguales a 1000 por ciudad, calcular su porcentaje respecto al total de transacciones de cada ciudad y obtener el monto máximo por ciudad.

               city  num_trans_200  num_trans_200_rate  max_amount_city
0         Monterrey              5                23.8          1307.99
1           Tijuana              5                15.2          4968.95
2            Cancún              3                 8.3          4211.94
3       Guadalajara              3                 5.3          1386.41
4   San Luis Potosí              3                15.0          6344.64
5  Ciudad de México              2                 4.7          1191.77
6            Toluca              1                 2.2          3630.96
7            Puebla              1                 4.3          1981.42
8            Mérida              1                10.0          1097.94
9         Querétaro              0                 0.0           468.92

ORDEN RECOMENDADO DE LAS CONSULTAS:
1. SELECT
2. FROM
3. JOIN
4. WHERE
5. GROUP BY
6. HAVING
7. ORDER BY

## CONSULTAS TIPO ENTREVISTA

### 1. Encuentra los **10 clientes que más dinero han gastado** en total.

Resultado esperado

La consulta debe devolver:

| customer_id | city | total_spent |
|---|---|---:|
| ... | ... | ... |

El resultado debe estar ordenado del cliente que **más gastó al que menos gastó**.

In [88]:
connection.rollback()

print("10 clientes que más han gastado en total")

pd.read_sql(
    "SELECT c.customer_id, c.city, SUM(t.amount) AS total_spend " \
    "FROM customers c " \
    "JOIN transactions t " \
    "   ON c.customer_id = t.customer_id " \
    "GROUP BY " \
    "   c.customer_id," \
    "   c.city " \
    "ORDER BY total_spend DESC " \
    "LIMIT 10;",
    connection
)

10 clientes que más han gastado en total

   customer_id              city  total_spend
0           27   San Luis Potosí      8535.01
1           33           Tijuana      8468.87
2           31            Toluca      6456.21
3           46            Cancún      6003.06
4           22           Tijuana      5431.76
5           20       Guadalajara      4204.00
6           38         Monterrey      3976.85
7            7            Cancún      3834.47
8           17           Tijuana      3754.28
9           36  Ciudad de México      3569.78

### 2. Calcula cuánto dinero se ha generado por cada **categoría de comercio**.

Resultado esperado

La consulta debe devolver:

| category | total_sales |
|---|---:|
| ... | ... |
| ... | ... |

Ordena el resultado de **mayor a menor venta**.

In [92]:
connection.rollback()

print("Dinero que se ha generado por cada categoría")

pd.read_sql(
    "SELECT m.category, SUM(t.amount) AS total_sales " \
    "FROM merchants m " \
    "JOIN transactions t " \
    "   ON m.merchant_id = t.merchant_id " \
    "GROUP BY m.category " \
    "ORDER BY total_sales DESC;",
    connection
)

Dinero que se ha generado por cada categoría

                  category  total_sales
0          Entretenimiento     19661.53
1   Tienda de conveniencia     15792.01
2               Gasolinera     14794.36
3     Restaurantes y cafés     14145.60
4               Transporte     13546.62
5             Supermercado     11592.70
6       Hogar y ferretería      8942.40
7            Departamental      8661.54
8               E-commerce      8101.84
9       Telecomunicaciones      4227.69
10                Farmacia      3513.76

### 3. Encuentra los clientes que hayan realizado **más de 10 transacciones**.

Resultado esperado

La consulta debe devolver:

| customer_id | transaction_count |
|---|---:|
| ... | ... |

Solo deben aparecer clientes que superen las **10 transacciones**.

Ordena el resultado de **mayor a menor número de transacciones**.

In [118]:
connection.rollback()

print("Clientes que realizaron más de 10 transacciones")

pd.read_sql(
    "SELECT customer_id, COUNT(transaction_id) AS transaction_count " \
    "FROM transactions " \
    "GROUP BY customer_id " \
    "HAVING COUNT(transaction_id) > 10",
    connection
)
# OPCIÓN CON CTE
#pd.read_sql(
#    "WITH help_count AS (" \
#    "   SELECT " \
#    "       customer_id, " \
#    "       COUNT(transaction_id) AS transaction_count " \
#    "   FROM transactions" \
#    "   GROUP BY customer_id" \
#    ")" \
#    "SELECT * " \
#    "FROM help_count " \
#    "WHERE transaction_count > 20",
#    connection
#)

Clientes que realizaron más de 10 transacciones

   customer_id  transaction_count
0           24                 11

### 4. Calcula el **monto promedio de transacción por ciudad**, considerando únicamente transacciones mayores a **$500 MXN**.

Resultado esperado

La consulta debe devolver:

| city | average_transaction |
|---|---:|
| ... | ... |
| ... | ... |

Ordena las ciudades de **mayor a menor ticket promedio**.

In [121]:
connection.rollback()

print("Monto promedio de transacciones por ciudad considerando solo transacciones mayores a $500")

pd.read_sql(
    "WITH trans_500 AS (" \
    "   SELECT c.city, t.amount " \
    "   FROM customers c " \
    "   JOIN transactions t " \
    "       ON c.customer_id = t.customer_id " \
    "   WHERE t.amount > 500) " \
    "SELECT city, AVG(amount) AS average_transaction " \
    "FROM trans_500 " \
    "GROUP BY city " \
    "ORDER BY average_transaction DESC",
    connection
)

Monto promedio de transacciones por ciudad considerando solo transacciones mayores a $500

               city  average_transaction
0           Tijuana          1747.787778
1   San Luis Potosí          1684.454286
2            Cancún          1516.995714
3         Monterrey          1150.658333
4            Toluca          1129.202500
5            Mérida          1097.940000
6            Puebla           960.040000
7       Guadalajara           862.877500
8  Ciudad de México           854.444444

### 5. Encuentra los **10 clientes que más han gastado**, mostrando:

- `customer_id`
- `city`
- cantidad de transacciones
- gasto total
- transacción promedio

Además, **solo deben aparecer clientes cuyo gasto total sea superior a $5,000 MXN**.

Resultado esperado

La consulta debe devolver:

| customer_id | city | transaction_count | total_spent | average_transaction |
|---|---|---:|---:|---:|
| ... | ... | ... | ... | ... |

Ordena por **gasto total descendente** y muestra únicamente los **10 primeros clientes**.

In [129]:
connection.rollback()

print("10 clientes que más han gastado")

pd.read_sql(
    "SELECT c.customer_id, c.city, COUNT(t.transaction_id) AS transaction_count, SUM(t.amount) AS total_spend, AVG(t.amount) AS average_transaction " \
    "FROM customers c " \
    "JOIN transactions t " \
    "   ON c.customer_id = t.customer_id " \
    "GROUP BY " \
    "   c.customer_id, " \
    "   c.city " \
    "HAVING SUM(t.amount) > 5000 " \
    "ORDER BY total_spend DESC " \
    "LIMIT 10",
    connection
)

10 clientes que más han gastado

,customer_id,city,transaction_count,total_spend,average_transaction
0,27,San Luis Potosí,6,8535.01,1422.501667
1,33,Tijuana,9,8468.87,940.985556
2,31,Toluca,8,6456.21,807.026250
3,46,Cancún,7,6003.06,857.580000
4,22,Tijuana,7,5431.76,775.965714

# Básico Pandas

In [130]:
import pandas as pd

customers = pd.read_sql(
    "SELECT * FROM customers",
    connection
)

merchants = pd.read_sql(
    "SELECT * FROM merchants",
    connection
)

payment_methods = pd.read_sql(
    "SELECT * FROM payment_methods",
    connection
)

transactions = pd.read_sql(
    "SELECT * FROM transactions",
    connection
)

In [144]:
print(customers.head())
print(customers.shape)
print(customers.columns)
print(customers.info())
print(customers["city"])

print(customers[
    (customers["age"] > 20)
    & (customers["age"] < 30)
])

print(customers.sort_values(
    "age",
    ascending=False
).head(10))

print(customers["age"].sum())
print(customers["age"].mean())
print(customers["age"].min())
print(customers["age"].max())
print(customers["age"].count())

   customer_id  age              city
0            1   58            Mérida
1            2   25         Monterrey
2            3   19           Tijuana
3            4   65   San Luis Potosí
4            5   35  Ciudad de México
(50, 3)
Index(['customer_id', 'age', 'city'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  50 non-null     int64
 1   age          50 non-null     int64
 2   city         50 non-null     str
dtypes: int64(2), str(1)
memory usage: 1.3 KB
None
0               Mérida
1            Monterrey
2              Tijuana
3      San Luis Potosí
4     Ciudad de México
5          Guadalajara
6               Cancún
7          Guadalajara
8               Mérida
9               Toluca
10    Ciudad de México
11              Cancún
12              Puebla
13    Ciudad de México
14         Guadalajara
15             Tijuana
16             Tijuana
17         Guadalajara
18              Puebla
19         Guadalajara
20              Cancún
21             Tijuana
22    Ciudad de México
23              Toluca
24         Guadalajara
25              Puebla
26     San Luis Potosí
27     San Luis Potosí
28              Toluca
29    Ciudad de México
30              Toluca
31              Toluca
32             Tijuana
33    Ciudad de México
34              Puebla
35    Ciudad de México
36              Cancún
37           Monterrey
38           Querétaro
39             Tijuana
40           Monterrey
41              Cancún
42         Guadalajara
43              Toluca
44           Querétaro
45              Cancún
46     San Luis Potosí
47           Monterrey
48         Guadalajara
49              Toluca
Name: city, dtype: str
    customer_id  age             city
1             2   25        Monterrey
7             8   26      Guadalajara
9            10   24           Toluca
14           15   23      Guadalajara
19           20   23      Guadalajara
41           42   28           Cancún
46           47   27  San Luis Potosí
    customer_id  age             city
12           13   75           Puebla
37           38   73        Monterrey
36           37   69           Cancún
40           41   69        Monterrey
39           40   66          Tijuana
48           49   66      Guadalajara
11           12   65           Cancún
8             9   65           Mérida
3             4   65  San Luis Potosí
27           28   63  San Luis Potosí
2206
44.12
18
75
50